// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

package ajni

/*
#include <jni.h>
#include "jni_call.h"
#include <stdlib.h>
*/
import "C"
import "unsafe"

// JNIDestroyJavaVM function as declared in android/jni_call.h:6
func JNIDestroyJavaVM(vm *JavaVM) Jint {
	cvm, _ := (*C.JavaVM)(unsafe.Pointer(vm)), cgoAllocsUnknown
	__ret := C.JNI_DestroyJavaVM(cvm)
	__v := (Jint)(__ret)
	return __v
}

// JNIAttachCurrentThread function as declared in android/jni_call.h:7
func JNIAttachCurrentThread(vm *JavaVM, pEnv **JNIEnv, thrArgs *C.JavaVMAttachArgs) Jint {
	cvm, _ := (*C.JavaVM)(unsafe.Pointer(vm)), cgoAllocsUnknown
	cpEnv, _ := (**C.JNIEnv)(unsafe.Pointer(pEnv)), cgoAllocsUnknown
	// cthrArgs, _ := thrArgs.PassRef()
	__ret := C.JNI_AttachCurrentThread(cvm, cpEnv, thrArgs)
	__v := (Jint)(__ret)
	return __v
}

// JNIDetachCurrentThread function as declared in android/jni_call.h:8
func JNIDetachCurrentThread(vm *JavaVM) Jint {
	cvm, _ := (*C.JavaVM)(unsafe.Pointer(vm)), cgoAllocsUnknown
	__ret := C.JNI_DetachCurrentThread(cvm)
	__v := (Jint)(__ret)
	return __v
}

// JNIGetEnv function as declared in android/jni_call.h:9
func JNIGetEnv(vm *JavaVM, pEnv **JNIEnv, version int32) Jint {
	cvm, _ := (*C.JavaVM)(unsafe.Pointer(vm)), cgoAllocsUnknown
	cpEnv, _ := (**C.JNIEnv)(unsafe.Pointer(pEnv)), cgoAllocsUnknown
	cversion, _ := (C.jint)(version), cgoAllocsUnknown
	__ret := C.JNI_GetEnv(cvm, cpEnv, cversion)
	__v := (Jint)(__ret)
	return __v
}

// JNIAttachCurrentThreadAsDaemon function as declared in android/jni_call.h:10
func JNIAttachCurrentThreadAsDaemon(vm *JavaVM, pEnv **JNIEnv, thrArgs unsafe.Pointer) Jint {
	cvm, _ := (*C.JavaVM)(unsafe.Pointer(vm)), cgoAllocsUnknown
	cpEnv, _ := (**C.JNIEnv)(unsafe.Pointer(pEnv)), cgoAllocsUnknown
	cthrArgs, _ := thrArgs, cgoAllocsUnknown
	__ret := C.JNI_AttachCurrentThreadAsDaemon(cvm, cpEnv, cthrArgs)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvGetVersion function as declared in android/jni_call.h:12
func JNIEnvGetVersion(env *JNIEnv) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetVersion(cenv)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvDefineClass function as declared in android/jni_call.h:14
func JNIEnvDefineClass(env *JNIEnv, name string, obj Jobject, buf []byte, bufLen int32) Jclass {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cbuf, _ := (*C.jbyte)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buf)).Data)), cgoAllocsUnknown
	cbufLen, _ := (C.jsize)(bufLen), cgoAllocsUnknown
	__ret := C.JNIEnv_DefineClass(cenv, cname, cobj, cbuf, cbufLen)
	__v := (Jclass)(__ret)
	return __v
}

// JNIEnvFindClass function as declared in android/jni_call.h:15
func JNIEnvFindClass(env *JNIEnv, name string) Jclass {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	__ret := C.JNIEnv_FindClass(cenv, cname)
	__v := (Jclass)(__ret)
	return __v
}

// JNIEnvFromReflectedMethod function as declared in android/jni_call.h:17
func JNIEnvFromReflectedMethod(env *JNIEnv, obj Jobject) JmethodID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_FromReflectedMethod(cenv, cobj)
	__v := *(*JmethodID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvFromReflectedField function as declared in android/jni_call.h:18
func JNIEnvFromReflectedField(env *JNIEnv, obj Jobject) JfieldID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_FromReflectedField(cenv, cobj)
	__v := *(*JfieldID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvToReflectedMethod function as declared in android/jni_call.h:19
func JNIEnvToReflectedMethod(env *JNIEnv, clazz Jclass, id JmethodID, isStatic byte) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cisStatic, _ := (C.jboolean)(isStatic), cgoAllocsUnknown
	__ret := C.JNIEnv_ToReflectedMethod(cenv, cclazz, cid, cisStatic)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvGetSuperclass function as declared in android/jni_call.h:21
func JNIEnvGetSuperclass(env *JNIEnv, clazz Jclass) Jclass {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	__ret := C.JNIEnv_GetSuperclass(cenv, cclazz)
	__v := (Jclass)(__ret)
	return __v
}

// JNIEnvIsAssignableFrom function as declared in android/jni_call.h:22
func JNIEnvIsAssignableFrom(env *JNIEnv, clazz1 Jclass, clazz2 Jclass) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz1, _ := (C.jclass)(clazz1), cgoAllocsUnknown
	cclazz2, _ := (C.jclass)(clazz2), cgoAllocsUnknown
	__ret := C.JNIEnv_IsAssignableFrom(cenv, cclazz1, cclazz2)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvToReflectedField function as declared in android/jni_call.h:24
func JNIEnvToReflectedField(env *JNIEnv, clazz Jclass, id JfieldID, isStatic byte) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cisStatic, _ := (C.jboolean)(isStatic), cgoAllocsUnknown
	__ret := C.JNIEnv_ToReflectedField(cenv, cclazz, cid, cisStatic)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvThrow function as declared in android/jni_call.h:26
func JNIEnvThrow(env *JNIEnv, ex *Jthrowable) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cex, _ := (C.jthrowable)(unsafe.Pointer(ex)), cgoAllocsUnknown
	__ret := C.JNIEnv_Throw(cenv, cex)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvThrowNew function as declared in android/jni_call.h:27
func JNIEnvThrowNew(env *JNIEnv, clazz Jclass, msg string) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cmsg, _ := unpackPCharString(msg)
	__ret := C.JNIEnv_ThrowNew(cenv, cclazz, cmsg)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvExceptionOccurred function as declared in android/jni_call.h:28
func JNIEnvExceptionOccurred(env *JNIEnv) *Jthrowable {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	__ret := C.JNIEnv_ExceptionOccurred(cenv)
	__v := *(**Jthrowable)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvExceptionDescribe function as declared in android/jni_call.h:29
func JNIEnvExceptionDescribe(env *JNIEnv) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	C.JNIEnv_ExceptionDescribe(cenv)
}

// JNIEnvExceptionClear function as declared in android/jni_call.h:30
func JNIEnvExceptionClear(env *JNIEnv) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	C.JNIEnv_ExceptionClear(cenv)
}

// JNIEnvFatalError function as declared in android/jni_call.h:31
func JNIEnvFatalError(env *JNIEnv, msg string) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cmsg, _ := unpackPCharString(msg)
	C.JNIEnv_FatalError(cenv, cmsg)
}

// JNIEnvPushLocalFrame function as declared in android/jni_call.h:33
func JNIEnvPushLocalFrame(env *JNIEnv, capacity int32) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	ccapacity, _ := (C.jint)(capacity), cgoAllocsUnknown
	__ret := C.JNIEnv_PushLocalFrame(cenv, ccapacity)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvPopLocalFrame function as declared in android/jni_call.h:34
func JNIEnvPopLocalFrame(env *JNIEnv, obj Jobject) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_PopLocalFrame(cenv, cobj)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvNewGlobalRef function as declared in android/jni_call.h:36
func JNIEnvNewGlobalRef(env *JNIEnv, ref Jobject) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cref, _ := (C.jobject)(ref), cgoAllocsUnknown
	__ret := C.JNIEnv_NewGlobalRef(cenv, cref)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvDeleteGlobalRef function as declared in android/jni_call.h:37
func JNIEnvDeleteGlobalRef(env *JNIEnv, ref Jobject) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cref, _ := (C.jobject)(ref), cgoAllocsUnknown
	C.JNIEnv_DeleteGlobalRef(cenv, cref)
}

// JNIEnvDeleteLocalRef function as declared in android/jni_call.h:38
func JNIEnvDeleteLocalRef(env *JNIEnv, ref Jobject) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cref, _ := (C.jobject)(ref), cgoAllocsUnknown
	C.JNIEnv_DeleteLocalRef(cenv, cref)
}

// JNIEnvIsSameObject function as declared in android/jni_call.h:39
func JNIEnvIsSameObject(env *JNIEnv, ref1 Jobject, ref2 Jobject) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cref1, _ := (C.jobject)(ref1), cgoAllocsUnknown
	cref2, _ := (C.jobject)(ref2), cgoAllocsUnknown
	__ret := C.JNIEnv_IsSameObject(cenv, cref1, cref2)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvNewLocalRef function as declared in android/jni_call.h:41
func JNIEnvNewLocalRef(env *JNIEnv, obj Jobject) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_NewLocalRef(cenv, cobj)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvEnsureLocalCapacity function as declared in android/jni_call.h:42
func JNIEnvEnsureLocalCapacity(env *JNIEnv, capacity int32) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	ccapacity, _ := (C.jint)(capacity), cgoAllocsUnknown
	__ret := C.JNIEnv_EnsureLocalCapacity(cenv, ccapacity)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvAllocObject function as declared in android/jni_call.h:44
func JNIEnvAllocObject(env *JNIEnv, clazz Jclass) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	__ret := C.JNIEnv_AllocObject(cenv, cclazz)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvNewObject function as declared in android/jni_call.h:45
func JNIEnvNewObject(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_NewObject(cenv, cclazz, cid, cargs)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvGetObjectClass function as declared in android/jni_call.h:47
func JNIEnvGetObjectClass(env *JNIEnv, obj Jobject) Jclass {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_GetObjectClass(cenv, cobj)
	__v := (Jclass)(__ret)
	return __v
}

// JNIEnvIsInstanceOf function as declared in android/jni_call.h:48
func JNIEnvIsInstanceOf(env *JNIEnv, obj Jobject, clazz Jclass) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	__ret := C.JNIEnv_IsInstanceOf(cenv, cobj, cclazz)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvGetMethodID function as declared in android/jni_call.h:49
func JNIEnvGetMethodID(env *JNIEnv, clazz Jclass, name string, sig string) JmethodID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	csig, _ := unpackPCharString(sig)
	__ret := C.JNIEnv_GetMethodID(cenv, cclazz, cname, csig)
	__v := *(*JmethodID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvCallObjectMethod function as declared in android/jni_call.h:51
func JNIEnvCallObjectMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallObjectMethod(cenv, cobj, cid, cargs)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvCallBooleanMethod function as declared in android/jni_call.h:52
func JNIEnvCallBooleanMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallBooleanMethod(cenv, cobj, cid, cargs)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvCallByteMethod function as declared in android/jni_call.h:53
func JNIEnvCallByteMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallByteMethod(cenv, cobj, cid, cargs)
	__v := (Jbyte)(__ret)
	return __v
}

// JNIEnvCallCharMethod function as declared in android/jni_call.h:54
func JNIEnvCallCharMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallCharMethod(cenv, cobj, cid, cargs)
	__v := (Jchar)(__ret)
	return __v
}

// JNIEnvCallShortMethod function as declared in android/jni_call.h:55
func JNIEnvCallShortMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallShortMethod(cenv, cobj, cid, cargs)
	__v := (Jshort)(__ret)
	return __v
}

// JNIEnvCallIntMethod function as declared in android/jni_call.h:56
func JNIEnvCallIntMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallIntMethod(cenv, cobj, cid, cargs)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvCallLongMethod function as declared in android/jni_call.h:57
func JNIEnvCallLongMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallLongMethod(cenv, cobj, cid, cargs)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvCallFloatMethod function as declared in android/jni_call.h:58
func JNIEnvCallFloatMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallFloatMethod(cenv, cobj, cid, cargs)
	__v := (Jfloat)(__ret)
	return __v
}

// JNIEnvCallDoubleMethod function as declared in android/jni_call.h:59
func JNIEnvCallDoubleMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallDoubleMethod(cenv, cobj, cid, cargs)
	__v := (Jdouble)(__ret)
	return __v
}

// JNIEnvCallVoidMethod function as declared in android/jni_call.h:60
func JNIEnvCallVoidMethod(env *JNIEnv, obj Jobject, id JmethodID, args []Jvalue) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	C.JNIEnv_CallVoidMethod(cenv, cobj, cid, cargs)
}

// JNIEnvCallNonvirtualObjectMethod function as declared in android/jni_call.h:62
func JNIEnvCallNonvirtualObjectMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualObjectMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvCallNonvirtualBooleanMethod function as declared in android/jni_call.h:63
func JNIEnvCallNonvirtualBooleanMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualBooleanMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvCallNonvirtualByteMethod function as declared in android/jni_call.h:64
func JNIEnvCallNonvirtualByteMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualByteMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jbyte)(__ret)
	return __v
}

// JNIEnvCallNonvirtualCharMethod function as declared in android/jni_call.h:65
func JNIEnvCallNonvirtualCharMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualCharMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jchar)(__ret)
	return __v
}

// JNIEnvCallNonvirtualShortMethod function as declared in android/jni_call.h:66
func JNIEnvCallNonvirtualShortMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualShortMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jshort)(__ret)
	return __v
}

// JNIEnvCallNonvirtualIntMethod function as declared in android/jni_call.h:67
func JNIEnvCallNonvirtualIntMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualIntMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvCallNonvirtualLongMethod function as declared in android/jni_call.h:68
func JNIEnvCallNonvirtualLongMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualLongMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvCallNonvirtualFloatMethod function as declared in android/jni_call.h:69
func JNIEnvCallNonvirtualFloatMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualFloatMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jfloat)(__ret)
	return __v
}

// JNIEnvCallNonvirtualDoubleMethod function as declared in android/jni_call.h:70
func JNIEnvCallNonvirtualDoubleMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallNonvirtualDoubleMethod(cenv, cobj, cclazz, cid, cargs)
	__v := (Jdouble)(__ret)
	return __v
}

// JNIEnvCallNonvirtualVoidMethod function as declared in android/jni_call.h:71
func JNIEnvCallNonvirtualVoidMethod(env *JNIEnv, obj Jobject, clazz Jclass, id JmethodID, args []Jvalue) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	C.JNIEnv_CallNonvirtualVoidMethod(cenv, cobj, cclazz, cid, cargs)
}

// JNIEnvGetFieldID function as declared in android/jni_call.h:73
func JNIEnvGetFieldID(env *JNIEnv, clazz Jclass, name string, sig string) JfieldID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	csig, _ := unpackPCharString(sig)
	__ret := C.JNIEnv_GetFieldID(cenv, cclazz, cname, csig)
	__v := *(*JfieldID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetObjectField function as declared in android/jni_call.h:75
func JNIEnvGetObjectField(env *JNIEnv, obj Jobject, id JfieldID) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetObjectField(cenv, cobj, cid)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvGetBooleanField function as declared in android/jni_call.h:76
func JNIEnvGetBooleanField(env *JNIEnv, obj Jobject, id JfieldID) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetBooleanField(cenv, cobj, cid)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvGetByteField function as declared in android/jni_call.h:77
func JNIEnvGetByteField(env *JNIEnv, obj Jobject, id JfieldID) Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetByteField(cenv, cobj, cid)
	__v := (Jbyte)(__ret)
	return __v
}

// JNIEnvGetCharField function as declared in android/jni_call.h:78
func JNIEnvGetCharField(env *JNIEnv, obj Jobject, id JfieldID) Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetCharField(cenv, cobj, cid)
	__v := (Jchar)(__ret)
	return __v
}

// JNIEnvGetShortField function as declared in android/jni_call.h:79
func JNIEnvGetShortField(env *JNIEnv, obj Jobject, id JfieldID) Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetShortField(cenv, cobj, cid)
	__v := (Jshort)(__ret)
	return __v
}

// JNIEnvGetIntField function as declared in android/jni_call.h:80
func JNIEnvGetIntField(env *JNIEnv, obj Jobject, id JfieldID) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetIntField(cenv, cobj, cid)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvGetLongField function as declared in android/jni_call.h:81
func JNIEnvGetLongField(env *JNIEnv, obj Jobject, id JfieldID) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetLongField(cenv, cobj, cid)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvGetFloatField function as declared in android/jni_call.h:82
func JNIEnvGetFloatField(env *JNIEnv, obj Jobject, id JfieldID) Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetFloatField(cenv, cobj, cid)
	__v := (Jfloat)(__ret)
	return __v
}

// JNIEnvGetDoubleField function as declared in android/jni_call.h:83
func JNIEnvGetDoubleField(env *JNIEnv, obj Jobject, id JfieldID) Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetDoubleField(cenv, cobj, cid)
	__v := (Jdouble)(__ret)
	return __v
}

// JNIEnvSetObjectField function as declared in android/jni_call.h:85
func JNIEnvSetObjectField(env *JNIEnv, obj Jobject, id JfieldID, val Jobject) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jobject)(val), cgoAllocsUnknown
	C.JNIEnv_SetObjectField(cenv, cobj, cid, cval)
}

// JNIEnvSetBooleanField function as declared in android/jni_call.h:86
func JNIEnvSetBooleanField(env *JNIEnv, obj Jobject, id JfieldID, val byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jboolean)(val), cgoAllocsUnknown
	C.JNIEnv_SetBooleanField(cenv, cobj, cid, cval)
}

// JNIEnvSetByteField function as declared in android/jni_call.h:87
func JNIEnvSetByteField(env *JNIEnv, obj Jobject, id JfieldID, val byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jbyte)(val), cgoAllocsUnknown
	C.JNIEnv_SetByteField(cenv, cobj, cid, cval)
}

// JNIEnvSetCharField function as declared in android/jni_call.h:88
func JNIEnvSetCharField(env *JNIEnv, obj Jobject, id JfieldID, val uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jchar)(val), cgoAllocsUnknown
	C.JNIEnv_SetCharField(cenv, cobj, cid, cval)
}

// JNIEnvSetShortField function as declared in android/jni_call.h:89
func JNIEnvSetShortField(env *JNIEnv, obj Jobject, id JfieldID, val int16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jshort)(val), cgoAllocsUnknown
	C.JNIEnv_SetShortField(cenv, cobj, cid, cval)
}

// JNIEnvSetIntField function as declared in android/jni_call.h:90
func JNIEnvSetIntField(env *JNIEnv, obj Jobject, id JfieldID, val int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jint)(val), cgoAllocsUnknown
	C.JNIEnv_SetIntField(cenv, cobj, cid, cval)
}

// JNIEnvSetLongField function as declared in android/jni_call.h:91
func JNIEnvSetLongField(env *JNIEnv, obj Jobject, id JfieldID, val int64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jlong)(val), cgoAllocsUnknown
	C.JNIEnv_SetLongField(cenv, cobj, cid, cval)
}

// JNIEnvSetFloatField function as declared in android/jni_call.h:92
func JNIEnvSetFloatField(env *JNIEnv, obj Jobject, id JfieldID, val float32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jfloat)(val), cgoAllocsUnknown
	C.JNIEnv_SetFloatField(cenv, cobj, cid, cval)
}

// JNIEnvSetDoubleField function as declared in android/jni_call.h:93
func JNIEnvSetDoubleField(env *JNIEnv, obj Jobject, id JfieldID, val float64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jdouble)(val), cgoAllocsUnknown
	C.JNIEnv_SetDoubleField(cenv, cobj, cid, cval)
}

// JNIEnvGetStaticMethodID function as declared in android/jni_call.h:95
func JNIEnvGetStaticMethodID(env *JNIEnv, clazz Jclass, name string, sig string) JmethodID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	csig, _ := unpackPCharString(sig)
	__ret := C.JNIEnv_GetStaticMethodID(cenv, cclazz, cname, csig)
	__v := *(*JmethodID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvCallStaticObjectMethod function as declared in android/jni_call.h:97
func JNIEnvCallStaticObjectMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticObjectMethod(cenv, cclazz, cid, cargs)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvCallStaticBooleanMethod function as declared in android/jni_call.h:98
func JNIEnvCallStaticBooleanMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticBooleanMethod(cenv, cclazz, cid, cargs)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvCallStaticByteMethod function as declared in android/jni_call.h:99
func JNIEnvCallStaticByteMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticByteMethod(cenv, cclazz, cid, cargs)
	__v := (Jbyte)(__ret)
	return __v
}

// JNIEnvCallStaticCharMethod function as declared in android/jni_call.h:100
func JNIEnvCallStaticCharMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticCharMethod(cenv, cclazz, cid, cargs)
	__v := (Jchar)(__ret)
	return __v
}

// JNIEnvCallStaticShortMethod function as declared in android/jni_call.h:101
func JNIEnvCallStaticShortMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticShortMethod(cenv, cclazz, cid, cargs)
	__v := (Jshort)(__ret)
	return __v
}

// JNIEnvCallStaticIntMethod function as declared in android/jni_call.h:102
func JNIEnvCallStaticIntMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticIntMethod(cenv, cclazz, cid, cargs)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvCallStaticLongMethod function as declared in android/jni_call.h:103
func JNIEnvCallStaticLongMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticLongMethod(cenv, cclazz, cid, cargs)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvCallStaticFloatMethod function as declared in android/jni_call.h:104
func JNIEnvCallStaticFloatMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticFloatMethod(cenv, cclazz, cid, cargs)
	__v := (Jfloat)(__ret)
	return __v
}

// JNIEnvCallStaticDoubleMethod function as declared in android/jni_call.h:105
func JNIEnvCallStaticDoubleMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	__ret := C.JNIEnv_CallStaticDoubleMethod(cenv, cclazz, cid, cargs)
	__v := (Jdouble)(__ret)
	return __v
}

// JNIEnvCallStaticVoidMethod function as declared in android/jni_call.h:106
func JNIEnvCallStaticVoidMethod(env *JNIEnv, clazz Jclass, id JmethodID, args []Jvalue) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jmethodID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cargs, _ := (*C.jvalue)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&args)).Data)), cgoAllocsUnknown
	C.JNIEnv_CallStaticVoidMethod(cenv, cclazz, cid, cargs)
}

// JNIEnvGetStaticFieldID function as declared in android/jni_call.h:108
func JNIEnvGetStaticFieldID(env *JNIEnv, clazz Jclass, name string, sig string) JfieldID {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cname, _ := unpackPCharString(name)
	csig, _ := unpackPCharString(sig)
	__ret := C.JNIEnv_GetStaticFieldID(cenv, cclazz, cname, csig)
	__v := *(*JfieldID)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetStaticObjectField function as declared in android/jni_call.h:110
func JNIEnvGetStaticObjectField(env *JNIEnv, clazz Jclass, id JfieldID) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticObjectField(cenv, cclazz, cid)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvGetStaticBooleanField function as declared in android/jni_call.h:111
func JNIEnvGetStaticBooleanField(env *JNIEnv, clazz Jclass, id JfieldID) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticBooleanField(cenv, cclazz, cid)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvGetStaticByteField function as declared in android/jni_call.h:112
func JNIEnvGetStaticByteField(env *JNIEnv, clazz Jclass, id JfieldID) Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticByteField(cenv, cclazz, cid)
	__v := (Jbyte)(__ret)
	return __v
}

// JNIEnvGetStaticCharField function as declared in android/jni_call.h:113
func JNIEnvGetStaticCharField(env *JNIEnv, clazz Jclass, id JfieldID) Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticCharField(cenv, cclazz, cid)
	__v := (Jchar)(__ret)
	return __v
}

// JNIEnvGetStaticShortField function as declared in android/jni_call.h:114
func JNIEnvGetStaticShortField(env *JNIEnv, clazz Jclass, id JfieldID) Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticShortField(cenv, cclazz, cid)
	__v := (Jshort)(__ret)
	return __v
}

// JNIEnvGetStaticIntField function as declared in android/jni_call.h:115
func JNIEnvGetStaticIntField(env *JNIEnv, clazz Jclass, id JfieldID) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticIntField(cenv, cclazz, cid)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvGetStaticLongField function as declared in android/jni_call.h:116
func JNIEnvGetStaticLongField(env *JNIEnv, clazz Jclass, id JfieldID) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticLongField(cenv, cclazz, cid)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvGetStaticFloatField function as declared in android/jni_call.h:117
func JNIEnvGetStaticFloatField(env *JNIEnv, clazz Jclass, id JfieldID) Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticFloatField(cenv, cclazz, cid)
	__v := (Jfloat)(__ret)
	return __v
}

// JNIEnvGetStaticDoubleField function as declared in android/jni_call.h:118
func JNIEnvGetStaticDoubleField(env *JNIEnv, clazz Jclass, id JfieldID) Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStaticDoubleField(cenv, cclazz, cid)
	__v := (Jdouble)(__ret)
	return __v
}

// JNIEnvSetStaticObjectField function as declared in android/jni_call.h:120
func JNIEnvSetStaticObjectField(env *JNIEnv, clazz Jclass, id JfieldID, val Jobject) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jobject)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticObjectField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticBooleanField function as declared in android/jni_call.h:121
func JNIEnvSetStaticBooleanField(env *JNIEnv, clazz Jclass, id JfieldID, val byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jboolean)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticBooleanField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticByteField function as declared in android/jni_call.h:122
func JNIEnvSetStaticByteField(env *JNIEnv, clazz Jclass, id JfieldID, val byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jbyte)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticByteField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticCharField function as declared in android/jni_call.h:123
func JNIEnvSetStaticCharField(env *JNIEnv, clazz Jclass, id JfieldID, val uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jchar)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticCharField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticShortField function as declared in android/jni_call.h:124
func JNIEnvSetStaticShortField(env *JNIEnv, clazz Jclass, id JfieldID, val int16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jshort)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticShortField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticIntField function as declared in android/jni_call.h:125
func JNIEnvSetStaticIntField(env *JNIEnv, clazz Jclass, id JfieldID, val int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jint)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticIntField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticLongField function as declared in android/jni_call.h:126
func JNIEnvSetStaticLongField(env *JNIEnv, clazz Jclass, id JfieldID, val int64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jlong)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticLongField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticFloatField function as declared in android/jni_call.h:127
func JNIEnvSetStaticFloatField(env *JNIEnv, clazz Jclass, id JfieldID, val float32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jfloat)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticFloatField(cenv, cclazz, cid, cval)
}

// JNIEnvSetStaticDoubleField function as declared in android/jni_call.h:128
func JNIEnvSetStaticDoubleField(env *JNIEnv, clazz Jclass, id JfieldID, val float64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cid, _ := *(*C.jfieldID)(unsafe.Pointer(&id)), cgoAllocsUnknown
	cval, _ := (C.jdouble)(val), cgoAllocsUnknown
	C.JNIEnv_SetStaticDoubleField(cenv, cclazz, cid, cval)
}

// JNIEnvNewString function as declared in android/jni_call.h:130
func JNIEnvNewString(env *JNIEnv, buf *uint16, bufLen int32) Jstring {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cbuf, _ := (*C.jchar)(unsafe.Pointer(buf)), cgoAllocsUnknown
	cbufLen, _ := (C.jsize)(bufLen), cgoAllocsUnknown
	__ret := C.JNIEnv_NewString(cenv, cbuf, cbufLen)
	__v := *(*Jstring)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetStringLength function as declared in android/jni_call.h:131
func JNIEnvGetStringLength(env *JNIEnv, str Jstring) Jsize {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStringLength(cenv, cstr)
	__v := (Jsize)(__ret)
	return __v
}

// JNIEnvGetStringChars function as declared in android/jni_call.h:132
func JNIEnvGetStringChars(env *JNIEnv, str Jstring, isCopy *byte) *Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStringChars(cenv, cstr, cisCopy)
	__v := *(**Jchar)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvReleaseStringChars function as declared in android/jni_call.h:133
func JNIEnvReleaseStringChars(env *JNIEnv, str Jstring, chars *uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cchars, _ := (*C.jchar)(unsafe.Pointer(chars)), cgoAllocsUnknown
	C.JNIEnv_ReleaseStringChars(cenv, cstr, cchars)
}

// JNIEnvNewStringUTF function as declared in android/jni_call.h:134
func JNIEnvNewStringUTF(env *JNIEnv, str string) Jstring {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := unpackPCharString(str)
	__ret := C.JNIEnv_NewStringUTF(cenv, cstr)
	__v := *(*Jstring)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetStringUTFLength function as declared in android/jni_call.h:135
func JNIEnvGetStringUTFLength(env *JNIEnv, str Jstring) Jsize {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStringUTFLength(cenv, cstr)
	__v := (Jsize)(__ret)
	return __v
}

// JNIEnvGetStringUTFChars function as declared in android/jni_call.h:136
func JNIEnvGetStringUTFChars(env *JNIEnv, str Jstring, isCopy *byte) string {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStringUTFChars(cenv, cstr, cisCopy)
	__v := packPCharString(__ret)
	return __v
}

// JNIEnvReleaseStringUTFChars function as declared in android/jni_call.h:137
func JNIEnvReleaseStringUTFChars(env *JNIEnv, str Jstring, utf string) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cutf, _ := unpackPCharString(utf)
	C.JNIEnv_ReleaseStringUTFChars(cenv, cstr, cutf)
}

// JNIEnvGetArrayLength function as declared in android/jni_call.h:138
func JNIEnvGetArrayLength(env *JNIEnv, arr Jarray) Jsize {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jarray)(arr), cgoAllocsUnknown
	__ret := C.JNIEnv_GetArrayLength(cenv, carr)
	__v := (Jsize)(__ret)
	return __v
}

// JNIEnvNewObjectArray function as declared in android/jni_call.h:139
func JNIEnvNewObjectArray(env *JNIEnv, length int32, clazz Jclass, obj Jobject) *JobjectArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_NewObjectArray(cenv, clength, cclazz, cobj)
	__v := *(**JobjectArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetObjectArrayElement function as declared in android/jni_call.h:140
func JNIEnvGetObjectArrayElement(env *JNIEnv, arr JobjectArray, index int32) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jobjectArray)(arr), cgoAllocsUnknown
	cindex, _ := (C.jsize)(index), cgoAllocsUnknown
	__ret := C.JNIEnv_GetObjectArrayElement(cenv, carr, cindex)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvSetObjectArrayElement function as declared in android/jni_call.h:141
func JNIEnvSetObjectArrayElement(env *JNIEnv, arr JobjectArray, index int32, obj Jobject) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jobjectArray)(arr), cgoAllocsUnknown
	cindex, _ := (C.jsize)(index), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	C.JNIEnv_SetObjectArrayElement(cenv, carr, cindex, cobj)
}

// JNIEnvNewBooleanArray function as declared in android/jni_call.h:143
func JNIEnvNewBooleanArray(env *JNIEnv, length int32) JbooleanArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewBooleanArray(cenv, clength)
	__v := *(*JbooleanArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewByteArray function as declared in android/jni_call.h:144
func JNIEnvNewByteArray(env *JNIEnv, length int32) JbyteArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewByteArray(cenv, clength)
	__v := *(*JbyteArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewCharArray function as declared in android/jni_call.h:145
func JNIEnvNewCharArray(env *JNIEnv, length int32) JcharArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewCharArray(cenv, clength)
	__v := *(*JcharArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewShortArray function as declared in android/jni_call.h:146
func JNIEnvNewShortArray(env *JNIEnv, length int32) JshortArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewShortArray(cenv, clength)
	__v := *(*JshortArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewIntArray function as declared in android/jni_call.h:147
func JNIEnvNewIntArray(env *JNIEnv, length int32) JintArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewIntArray(cenv, clength)
	__v := *(*JintArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewLongArray function as declared in android/jni_call.h:148
func JNIEnvNewLongArray(env *JNIEnv, length int32) JlongArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewLongArray(cenv, clength)
	__v := *(*JlongArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewFloatArray function as declared in android/jni_call.h:149
func JNIEnvNewFloatArray(env *JNIEnv, length int32) JfloatArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewFloatArray(cenv, clength)
	__v := *(*JfloatArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvNewDoubleArray function as declared in android/jni_call.h:150
func JNIEnvNewDoubleArray(env *JNIEnv, length int32) JdoubleArray {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	__ret := C.JNIEnv_NewDoubleArray(cenv, clength)
	__v := *(*JdoubleArray)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetBooleanArrayElements function as declared in android/jni_call.h:152
func JNIEnvGetBooleanArrayElements(env *JNIEnv, arr JbooleanArray, isCopy *byte) *Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbooleanArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetBooleanArrayElements(cenv, carr, cisCopy)
	__v := *(**Jboolean)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetByteArrayElements function as declared in android/jni_call.h:153
func JNIEnvGetByteArrayElements(env *JNIEnv, arr JbyteArray, isCopy *byte) *Jbyte {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbyteArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetByteArrayElements(cenv, carr, cisCopy)
	__v := *(**Jbyte)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetCharArrayElements function as declared in android/jni_call.h:154
func JNIEnvGetCharArrayElements(env *JNIEnv, arr JcharArray, isCopy *byte) *Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jcharArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetCharArrayElements(cenv, carr, cisCopy)
	__v := *(**Jchar)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetShortArrayElements function as declared in android/jni_call.h:155
func JNIEnvGetShortArrayElements(env *JNIEnv, arr JshortArray, isCopy *byte) *Jshort {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jshortArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetShortArrayElements(cenv, carr, cisCopy)
	__v := *(**Jshort)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetIntArrayElements function as declared in android/jni_call.h:156
func JNIEnvGetIntArrayElements(env *JNIEnv, arr JintArray, isCopy *byte) *Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jintArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetIntArrayElements(cenv, carr, cisCopy)
	__v := *(**Jint)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetLongArrayElements function as declared in android/jni_call.h:157
func JNIEnvGetLongArrayElements(env *JNIEnv, arr JlongArray, isCopy *byte) *Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jlongArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetLongArrayElements(cenv, carr, cisCopy)
	__v := *(**Jlong)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetFloatArrayElements function as declared in android/jni_call.h:158
func JNIEnvGetFloatArrayElements(env *JNIEnv, arr JfloatArray, isCopy *byte) *Jfloat {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jfloatArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetFloatArrayElements(cenv, carr, cisCopy)
	__v := *(**Jfloat)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetDoubleArrayElements function as declared in android/jni_call.h:159
func JNIEnvGetDoubleArrayElements(env *JNIEnv, arr JdoubleArray, isCopy *byte) *Jdouble {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jdoubleArray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetDoubleArrayElements(cenv, carr, cisCopy)
	__v := *(**Jdouble)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvReleaseBooleanArrayElements function as declared in android/jni_call.h:161
func JNIEnvReleaseBooleanArrayElements(env *JNIEnv, arr JbooleanArray, elems *byte, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbooleanArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jboolean)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseBooleanArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseByteArrayElements function as declared in android/jni_call.h:162
func JNIEnvReleaseByteArrayElements(env *JNIEnv, arr JbyteArray, elems *byte, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbyteArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jbyte)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseByteArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseCharArrayElements function as declared in android/jni_call.h:163
func JNIEnvReleaseCharArrayElements(env *JNIEnv, arr JcharArray, elems *uint16, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jcharArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jchar)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseCharArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseShortArrayElements function as declared in android/jni_call.h:164
func JNIEnvReleaseShortArrayElements(env *JNIEnv, arr JshortArray, elems *int16, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jshortArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jshort)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseShortArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseIntArrayElements function as declared in android/jni_call.h:165
func JNIEnvReleaseIntArrayElements(env *JNIEnv, arr JintArray, elems *int32, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jintArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jint)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseIntArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseLongArrayElements function as declared in android/jni_call.h:166
func JNIEnvReleaseLongArrayElements(env *JNIEnv, arr JlongArray, elems *int64, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jlongArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jlong)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseLongArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseFloatArrayElements function as declared in android/jni_call.h:167
func JNIEnvReleaseFloatArrayElements(env *JNIEnv, arr JfloatArray, elems *float32, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jfloatArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jfloat)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseFloatArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvReleaseDoubleArrayElements function as declared in android/jni_call.h:168
func JNIEnvReleaseDoubleArrayElements(env *JNIEnv, arr JdoubleArray, elems *float64, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jdoubleArray)(arr), cgoAllocsUnknown
	celems, _ := (*C.jdouble)(unsafe.Pointer(elems)), cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleaseDoubleArrayElements(cenv, carr, celems, cmode)
}

// JNIEnvGetBooleanArrayRegion function as declared in android/jni_call.h:170
func JNIEnvGetBooleanArrayRegion(env *JNIEnv, arr JbooleanArray, start int32, length int32, buf *byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbooleanArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jboolean)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetBooleanArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetByteArrayRegion function as declared in android/jni_call.h:171
func JNIEnvGetByteArrayRegion(env *JNIEnv, arr JbyteArray, start int32, length int32, buf *byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbyteArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jbyte)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetByteArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetCharArrayRegion function as declared in android/jni_call.h:172
func JNIEnvGetCharArrayRegion(env *JNIEnv, arr JcharArray, start int32, length int32, buf *uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jcharArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jchar)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetCharArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetShortArrayRegion function as declared in android/jni_call.h:173
func JNIEnvGetShortArrayRegion(env *JNIEnv, arr JshortArray, start int32, length int32, buf *int16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jshortArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jshort)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetShortArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetIntArrayRegion function as declared in android/jni_call.h:174
func JNIEnvGetIntArrayRegion(env *JNIEnv, arr JintArray, start int32, length int32, buf *int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jintArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jint)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetIntArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetLongArrayRegion function as declared in android/jni_call.h:175
func JNIEnvGetLongArrayRegion(env *JNIEnv, arr JlongArray, start int32, length int32, buf *int64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jlongArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jlong)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetLongArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetFloatArrayRegion function as declared in android/jni_call.h:176
func JNIEnvGetFloatArrayRegion(env *JNIEnv, arr JfloatArray, start int32, length int32, buf *float32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jfloatArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jfloat)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetFloatArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvGetDoubleArrayRegion function as declared in android/jni_call.h:177
func JNIEnvGetDoubleArrayRegion(env *JNIEnv, arr JdoubleArray, start int32, length int32, buf *float64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jdoubleArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jdouble)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetDoubleArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetBooleanArrayRegion function as declared in android/jni_call.h:179
func JNIEnvSetBooleanArrayRegion(env *JNIEnv, arr JbooleanArray, start int32, length int32, buf *byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbooleanArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jboolean)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetBooleanArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetByteArrayRegion function as declared in android/jni_call.h:180
func JNIEnvSetByteArrayRegion(env *JNIEnv, arr JbyteArray, start int32, length int32, buf *byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jbyteArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jbyte)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetByteArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetCharArrayRegion function as declared in android/jni_call.h:181
func JNIEnvSetCharArrayRegion(env *JNIEnv, arr JcharArray, start int32, length int32, buf *uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jcharArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jchar)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetCharArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetShortArrayRegion function as declared in android/jni_call.h:182
func JNIEnvSetShortArrayRegion(env *JNIEnv, arr JshortArray, start int32, length int32, buf *int16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jshortArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jshort)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetShortArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetIntArrayRegion function as declared in android/jni_call.h:183
func JNIEnvSetIntArrayRegion(env *JNIEnv, arr JintArray, start int32, length int32, buf *int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jintArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jint)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetIntArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetLongArrayRegion function as declared in android/jni_call.h:184
func JNIEnvSetLongArrayRegion(env *JNIEnv, arr JlongArray, start int32, length int32, buf *int64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jlongArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jlong)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetLongArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetFloatArrayRegion function as declared in android/jni_call.h:185
func JNIEnvSetFloatArrayRegion(env *JNIEnv, arr JfloatArray, start int32, length int32, buf *float32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jfloatArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jfloat)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetFloatArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvSetDoubleArrayRegion function as declared in android/jni_call.h:186
func JNIEnvSetDoubleArrayRegion(env *JNIEnv, arr JdoubleArray, start int32, length int32, buf *float64) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jdoubleArray)(arr), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jdouble)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_SetDoubleArrayRegion(cenv, carr, cstart, clength, cbuf)
}

// JNIEnvRegisterNatives function as declared in android/jni_call.h:188
func JNIEnvRegisterNatives(env *JNIEnv, clazz Jclass, methods *JNINativeMethod, nMethods int32) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	cmethods, _ := (*C.JNINativeMethod)(unsafe.Pointer(methods)), cgoAllocsUnknown
	cnMethods, _ := (C.jint)(nMethods), cgoAllocsUnknown
	__ret := C.JNIEnv_RegisterNatives(cenv, cclazz, cmethods, cnMethods)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvUnregisterNatives function as declared in android/jni_call.h:189
func JNIEnvUnregisterNatives(env *JNIEnv, clazz Jclass) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cclazz, _ := (C.jclass)(clazz), cgoAllocsUnknown
	__ret := C.JNIEnv_UnregisterNatives(cenv, cclazz)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvMonitorEnter function as declared in android/jni_call.h:190
func JNIEnvMonitorEnter(env *JNIEnv, obj Jobject) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_MonitorEnter(cenv, cobj)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvMonitorExit function as declared in android/jni_call.h:191
func JNIEnvMonitorExit(env *JNIEnv, obj Jobject) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_MonitorExit(cenv, cobj)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvGetJavaVM function as declared in android/jni_call.h:192
func JNIEnvGetJavaVM(env *JNIEnv, pVm **JavaVM) Jint {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cpVm, _ := (**C.JavaVM)(unsafe.Pointer(pVm)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetJavaVM(cenv, cpVm)
	__v := (Jint)(__ret)
	return __v
}

// JNIEnvGetStringRegion function as declared in android/jni_call.h:194
func JNIEnvGetStringRegion(env *JNIEnv, str Jstring, start int32, length int32, buf *uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.jchar)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetStringRegion(cenv, cstr, cstart, clength, cbuf)
}

// JNIEnvGetStringUTFRegion function as declared in android/jni_call.h:195
func JNIEnvGetStringUTFRegion(env *JNIEnv, str Jstring, start int32, length int32, buf *byte) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cstart, _ := (C.jsize)(start), cgoAllocsUnknown
	clength, _ := (C.jsize)(length), cgoAllocsUnknown
	cbuf, _ := (*C.char)(unsafe.Pointer(buf)), cgoAllocsUnknown
	C.JNIEnv_GetStringUTFRegion(cenv, cstr, cstart, clength, cbuf)
}

// JNIEnvGetPrimitiveArrayCritical function as declared in android/jni_call.h:197
func JNIEnvGetPrimitiveArrayCritical(env *JNIEnv, arr Jarray, isCopy *byte) unsafe.Pointer {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jarray)(arr), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetPrimitiveArrayCritical(cenv, carr, cisCopy)
	__v := *(*unsafe.Pointer)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvReleasePrimitiveArrayCritical function as declared in android/jni_call.h:198
func JNIEnvReleasePrimitiveArrayCritical(env *JNIEnv, arr Jarray, carray unsafe.Pointer, mode int32) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	carr, _ := (C.jarray)(arr), cgoAllocsUnknown
	ccarray, _ := carray, cgoAllocsUnknown
	cmode, _ := (C.jint)(mode), cgoAllocsUnknown
	C.JNIEnv_ReleasePrimitiveArrayCritical(cenv, carr, ccarray, cmode)
}

// JNIEnvGetStringCritical function as declared in android/jni_call.h:200
func JNIEnvGetStringCritical(env *JNIEnv, str Jstring, isCopy *byte) *Jchar {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	cisCopy, _ := (*C.jboolean)(unsafe.Pointer(isCopy)), cgoAllocsUnknown
	__ret := C.JNIEnv_GetStringCritical(cenv, cstr, cisCopy)
	__v := *(**Jchar)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvReleaseStringCritical function as declared in android/jni_call.h:201
func JNIEnvReleaseStringCritical(env *JNIEnv, str Jstring, carray *uint16) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cstr, _ := (C.jstring)(str), cgoAllocsUnknown
	ccarray, _ := (*C.jchar)(unsafe.Pointer(carray)), cgoAllocsUnknown
	C.JNIEnv_ReleaseStringCritical(cenv, cstr, ccarray)
}

// JNIEnvNewWeakGlobalRef function as declared in android/jni_call.h:203
func JNIEnvNewWeakGlobalRef(env *JNIEnv, obj Jobject) *Jweak {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_NewWeakGlobalRef(cenv, cobj)
	__v := *(**Jweak)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvDeleteWeakGlobalRef function as declared in android/jni_call.h:204
func JNIEnvDeleteWeakGlobalRef(env *JNIEnv, obj *Jweak) {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jweak)(unsafe.Pointer(obj)), cgoAllocsUnknown
	C.JNIEnv_DeleteWeakGlobalRef(cenv, cobj)
}

// JNIEnvExceptionCheck function as declared in android/jni_call.h:206
func JNIEnvExceptionCheck(env *JNIEnv) Jboolean {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	__ret := C.JNIEnv_ExceptionCheck(cenv)
	__v := (Jboolean)(__ret)
	return __v
}

// JNIEnvNewDirectByteBuffer function as declared in android/jni_call.h:208
func JNIEnvNewDirectByteBuffer(env *JNIEnv, buf unsafe.Pointer, capacity int64) Jobject {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cbuf, _ := buf, cgoAllocsUnknown
	ccapacity, _ := (C.jlong)(capacity), cgoAllocsUnknown
	__ret := C.JNIEnv_NewDirectByteBuffer(cenv, cbuf, ccapacity)
	__v := (Jobject)(__ret)
	return __v
}

// JNIEnvGetDirectBufferAddress function as declared in android/jni_call.h:209
func JNIEnvGetDirectBufferAddress(env *JNIEnv, buf Jobject) unsafe.Pointer {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cbuf, _ := (C.jobject)(buf), cgoAllocsUnknown
	__ret := C.JNIEnv_GetDirectBufferAddress(cenv, cbuf)
	__v := *(*unsafe.Pointer)(unsafe.Pointer(&__ret))
	return __v
}

// JNIEnvGetDirectBufferCapacity function as declared in android/jni_call.h:210
func JNIEnvGetDirectBufferCapacity(env *JNIEnv, buf Jobject) Jlong {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cbuf, _ := (C.jobject)(buf), cgoAllocsUnknown
	__ret := C.JNIEnv_GetDirectBufferCapacity(cenv, cbuf)
	__v := (Jlong)(__ret)
	return __v
}

// JNIEnvGetObjectRefType function as declared in android/jni_call.h:212
func JNIEnvGetObjectRefType(env *JNIEnv, obj Jobject) JobjectRefType {
	cenv, _ := (*C.JNIEnv)(unsafe.Pointer(env)), cgoAllocsUnknown
	cobj, _ := (C.jobject)(obj), cgoAllocsUnknown
	__ret := C.JNIEnv_GetObjectRefType(cenv, cobj)
	__v := (JobjectRefType)(__ret)
	return __v
}
