// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

package ajni

/*
#cgo LDFLAGS: -landroid -llog
// #include <android/api-level.h>
// #include <android/asset_manager.h>
// #include <android/asset_manager_jni.h>
// #include <android/configuration.h>
// #include <android/input.h>
// #include <android/keycodes.h>
// #include <android/log.h>
// #include <android/looper.h>
// #include <android/native_activity.h>
// #include <android/native_window.h>
// #include <android/native_window_jni.h>
// #include <android/obb.h>
// #include <android/rect.h>
// #include <android/sensor.h>
// #include <android/storage_manager.h>
// #include <android/window.h>
#include <jni.h>
#include "jni_call.h"
#include <stdlib.h>
// #include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Jboolean type as declared in include/jni.h:44
type Jboolean byte

// Jbyte type as declared in include/jni.h:45
type Jbyte byte

// Jchar type as declared in include/jni.h:46
type Jchar uint16

// Jshort type as declared in include/jni.h:47
type Jshort int16

// Jint type as declared in include/jni.h:48
type Jint int32

// Jlong type as declared in include/jni.h:49
type Jlong int64

// Jfloat type as declared in include/jni.h:50
type Jfloat float32

// Jdouble type as declared in include/jni.h:51
type Jdouble float64

// Jsize type as declared in include/jni.h:55
type Jsize int32

// Jobject type as declared in include/jni.h:98
type Jobject uintptr

// Jclass type as declared in include/jni.h:99
type Jclass uintptr

// Jstring type as declared in include/jni.h:100
type Jstring uintptr

// Jarray type as declared in include/jni.h:101
type Jarray uintptr

// JobjectArray type as declared in include/jni.h:102
type JobjectArray uintptr

// JbooleanArray type as declared in include/jni.h:103
type JbooleanArray uintptr

// JbyteArray type as declared in include/jni.h:104
type JbyteArray uintptr

// JcharArray type as declared in include/jni.h:105
type JcharArray uintptr

// JshortArray type as declared in include/jni.h:106
type JshortArray uintptr

// JintArray type as declared in include/jni.h:107
type JintArray uintptr

// JlongArray type as declared in include/jni.h:108
type JlongArray uintptr

// JfloatArray type as declared in include/jni.h:109
type JfloatArray uintptr

// JdoubleArray type as declared in include/jni.h:110
type JdoubleArray uintptr

// Jthrowable type as declared in include/jni.h:111
type Jthrowable uintptr

// Jweak type as declared in include/jni.h:112
type Jweak uintptr

// JfieldID as declared in include/jni.h:117
type JfieldID C.jfieldID

// JmethodID as declared in include/jni.h:120
type JmethodID C.jmethodID

// Jvalue as declared in include/jni.h:134
const sizeofJvalue = unsafe.Sizeof(C.jvalue{})

type Jvalue [sizeofJvalue]byte

// JNINativeMethod as declared in include/jni.h:147
type JNINativeMethod C.JNINativeMethod

// JNIEnv as declared in include/jni.h:157
type JNIEnv C.JNIEnv

// JavaVM as declared in include/jni.h:158
type JavaVM C.JavaVM

// JavaVMAttachArgs as declared in include/jni.h:1106
type JavaVMAttachArgs struct {
	Version        Jint
	Name           string
	Group          Jobject
	refab42f020    *C.JavaVMAttachArgs
	allocsab42f020 interface{}
}

// JavaVMOption as declared in include/jni.h:1115
type JavaVMOption C.JavaVMOption

// JavaVMInitArgs as declared in include/jni.h:1123
type JavaVMInitArgs C.JavaVMInitArgs
